[project]
name = "ottimizzatore-lauree"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "advanced-alchemy>=1.4.5",
    "aio-pika>=9.5.5",
    "aiosqlite>=0.21.0",
    "alembic>=1.16.4",
    "flask>=3.1.1",
    "flask-cors>=6.0.1",
    "litestar[standard]>=2.16.0",
    "msgspec>=0.19.0",
    "mypy>=1.17.1",
    "numpy>=2.3.2",
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pandas-stubs==2.3.0.250703",
    "psycopg2-binary>=2.9.10",
    "psycopg[binary]>=3.2.9",
    "pyarrow>=21.0.0",
    "pydantic>=2.11.7",
    "pyomo>=6.9.2",
    "python-dotenv>=1.1.1",
    "python-multipart>=0.0.20",
    "rich>=14.1.0",
    "sqlalchemy>=2.0.42",
    "structlog>=25.4.0",
    "types-pyyaml>=6.0.12.20250809",
    "watchdog>=6.0.0",
    "xlrd>=2.0.2",
]

[[tool.mypy.overrides]]
module = "pyomo.*"
ignore_missing_imports = true

