import type {RequestHandler} from './$types';
import {backendResponse} from "$lib/server/backend";

/** Downloads the commissions of the configuration's solution as an Excel file (generated by the backend). */
export const GET: RequestHandler = async ({params}) => {
  const response = await backendResponse(`/sessions/${params.id}/configuration/${params.conf_id}/export`);

  return new Response(response.body, {
    headers: {
      "Content-Type": response.headers.get("Content-Type") ?? "application/octet-stream",
      "Content-Disposition": response.headers.get("Content-Disposition") ?? "attachment",
    }
  });
};
