"""Professors Split

Revision ID: e67bf411b46e
Revises: a55ee52d742e
Create Date: 2024-08-24 16:47:30.979176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e67bf411b46e'
down_revision: Union[str, None] = 'a55ee52d742e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# https://stackoverflow.com/questions/14845203/altering-an-enum-field-using-alembic

old_options = ('MORNING', 'AFTERNOON', 'ALWAYS')
new_options = sorted(old_options + ('SPLIT',))

time_availability_enum_old = sa.Enum(*old_options, name='time_availability')
time_availability_enum_new = sa.Enum(*new_options, name='time_availability')
tmp_type = sa.Enum(*old_options, name='_time_availability')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('alter type time_availability add value \'SPLIT\' after \'ALWAYS\'')
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError("Downgrade from this version is not possible.")
