"""Optimization Structures

Revision ID: 5a12fd3194ad
Revises: 97615298b642
Create Date: 2025-07-13 13:49:20.990889

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = '5a12fd3194ad'
down_revision = '97615298b642'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('optimization_configurations',
    sa.Column('title', sa.String(length=256), server_default='Nuova configurazione', nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('max_duration', sa.Integer(), server_default='210', nullable=False),
    sa.Column('max_commissions_morning', sa.Integer(), server_default='6', nullable=False),
    sa.Column('max_commissions_afternoon', sa.Integer(), server_default='6', nullable=False),
    sa.Column('online', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('min_professor_number', sa.Integer(), nullable=True),
    sa.Column('min_professor_number_masters', sa.Integer(), nullable=True),
    sa.Column('max_professor_numer', sa.Integer(), nullable=True),
    sa.Column('solver', sa.Enum('CPLEX', 'GLPK', 'GUROBI', name='solverenum'), server_default='CPLEX', nullable=False),
    sa.Column('optimization_time_limit', sa.Integer(), server_default='60', nullable=False),
    sa.Column('optimization_gap', sa.Float(), server_default='0.005', nullable=False),
    sa.Column('run_lock', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_optimization_configurations_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_configurations'))
    )
    op.create_table('optimization_logs',
    sa.Column('opt_config_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opt_config_id'], ['optimization_configurations.id'], name=op.f('fk_optimization_logs_opt_config_id_optimization_configurations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_logs'))
    )
    op.create_table('solution_commissions',
    sa.Column('order_key', sa.Integer(), nullable=False),
    sa.Column('morning', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('opt_config_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opt_config_id'], ['optimization_configurations.id'], name=op.f('fk_solution_commissions_opt_config_id_optimization_configurations')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_solution_commissions_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution_commissions')),
    sa.UniqueConstraint('session_id', 'order_key', 'opt_config_id', name=op.f('uq_solution_commissions_session_id'))
    )
    op.create_table('solution_commission_professors',
    sa.Column('solution_commission_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_solution_commission_professors_professor_id_professors')),
    sa.ForeignKeyConstraint(['solution_commission_id'], ['solution_commissions.id'], name=op.f('fk_solution_commission_professors_solution_commission_id_solution_commissions')),
    sa.PrimaryKeyConstraint('solution_commission_id', 'professor_id', name=op.f('pk_solution_commission_professors'))
    )
    op.create_table('solution_commission_students',
    sa.Column('solution_commission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_commission_id'], ['solution_commissions.id'], name=op.f('fk_solution_commission_students_solution_commission_id_solution_commissions')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_solution_commission_students_student_id_students')),
    sa.PrimaryKeyConstraint('solution_commission_id', 'student_id', name=op.f('pk_solution_commission_students'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solution_commission_students')
    op.drop_table('solution_commission_professors')
    op.drop_table('solution_commissions')
    op.drop_table('optimization_logs')
    op.drop_table('optimization_configurations')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
