"""opt_conf_online_check

Revision ID: 918beebccab0
Revises: 5a12fd3194ad
Create Date: 2025-07-16 18:58:37.300229

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, \
    PasswordHash
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = '918beebccab0'
down_revision = '5a12fd3194ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()


def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()


def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimization_configurations', schema=None) as batch_op:
        batch_op.alter_column('max_professor_numer', new_column_name='max_professor_number')
    # ### end Alembic commands ###


def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimization_configurations', schema=None) as batch_op:
        batch_op.drop_constraint('ck_online_requires_professor_numbers', type_='check')

        batch_op.alter_column('max_professor_number', new_column_name='max_professor_numer')

    # ### end Alembic commands ###


def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""
    # Fix invalid rows before adding the constraint
    connection = op.get_bind()

    # Set online = FALSE for rows that have online = TRUE but missing professor numbers
    connection.execute(
        sa.text("""
                UPDATE optimization_configurations
                SET online = FALSE
                WHERE online = TRUE
                  AND (
                    min_professor_number IS NULL
                        OR min_professor_number_masters IS NULL
                        OR max_professor_number IS NULL
                    )
                """)
    )

    # Now add the constraint after fixing the data
    op.create_check_constraint(
        'ck_online_requires_professor_numbers',
        'optimization_configurations',
        'NOT online OR (min_professor_number IS NOT NULL AND min_professor_number_masters IS NOT NULL AND max_professor_number IS NOT NULL)'
    )


def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
