"""session professor delete restriction

Revision ID: 3558a37945a0
Revises: 46b39cb4c9b0
Create Date: 2025-08-11 01:06:28.038834

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = '3558a37945a0'
down_revision = '46b39cb4c9b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_session_entries_counter_supervisor_id_session_professors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_session_entries_supervisor_id_session_professors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_session_entries_supervisor2_id_session_professors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_session_entries_supervisor_assistant_id_session_professors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_supervisor_assistant_id_session_professors'), 'session_professors', ['supervisor_assistant_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_counter_supervisor_id_session_professors'), 'session_professors', ['counter_supervisor_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_supervisor2_id_session_professors'), 'session_professors', ['supervisor2_id'], ['id'], ondelete='RESTRICT')
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_supervisor_id_session_professors'), 'session_professors', ['supervisor_id'], ['id'], ondelete='RESTRICT')

    with op.batch_alter_table('session_professors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_professors_derived_from_id'), ['derived_from_id'], unique=False)

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_professors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_professors_derived_from_id'))

    with op.batch_alter_table('session_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_session_entries_supervisor_id_session_professors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_session_entries_supervisor2_id_session_professors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_session_entries_counter_supervisor_id_session_professors'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_session_entries_supervisor_assistant_id_session_professors'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_supervisor_assistant_id_session_professors'), 'session_professors', ['supervisor_assistant_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_supervisor2_id_session_professors'), 'session_professors', ['supervisor2_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_supervisor_id_session_professors'), 'session_professors', ['supervisor_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_session_entries_counter_supervisor_id_session_professors'), 'session_professors', ['counter_supervisor_id'], ['id'])

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
