"""v2.1

Revision ID: 9f68d04a05bc
Revises: 
Create Date: 2025-08-05 17:00:44.174125

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = '9f68d04a05bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ORDINARY', 'ASSOCIATE', 'RESEARCHER', 'UNSPECIFIED', name='university_role_enum'), server_default='UNSPECIFIED', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professors'))
    )
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.create_index('idx_professors_name_surname_unique', ['first_name', 'surname'], unique=True)

    op.create_table('sessions',
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sessions'))
    )
    op.create_table('students',
    sa.Column('matriculation_number', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('surname', sa.String(length=128), nullable=False),
    sa.Column('phone_number', sa.String(length=128), nullable=False),
    sa.Column('personal_email', sa.String(length=128), nullable=False),
    sa.Column('university_email', sa.String(length=128), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_students'))
    )
    op.create_table('optimization_configurations',
    sa.Column('title', sa.String(length=256), server_default='Nuova configurazione', nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('max_duration', sa.Integer(), server_default='210', nullable=False),
    sa.Column('max_commissions_morning', sa.Integer(), server_default='6', nullable=False),
    sa.Column('max_commissions_afternoon', sa.Integer(), server_default='6', nullable=False),
    sa.Column('online', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('min_professor_number', sa.Integer(), nullable=True),
    sa.Column('min_professor_number_masters', sa.Integer(), nullable=True),
    sa.Column('max_professor_number', sa.Integer(), nullable=True),
    sa.Column('solver', sa.Enum('CPLEX', 'GLPK', 'GUROBI', name='solver_enum'), server_default='CPLEX', nullable=False),
    sa.Column('optimization_time_limit', sa.Integer(), server_default='60', nullable=False),
    sa.Column('optimization_gap', sa.Float(), server_default='0.005', nullable=False),
    sa.Column('run_lock', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint('NOT online OR (min_professor_number IS NOT NULL AND min_professor_number_masters IS NOT NULL AND max_professor_number IS NOT NULL)', name=op.f('ck_optimization_configurations_ck_online_requires_professor_numbers')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_optimization_configurations_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_configurations'))
    )
    op.create_table('session_professors',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('professor_id', sa.BigInteger(), nullable=False),
    sa.Column('relation', sa.Enum('ORIGINAL', 'SPLIT', 'SUBSTITUTE', name='session_professor_relation_enum'), nullable=False),
    sa.Column('derived_from_id', sa.BigInteger(), nullable=True),
    sa.Column('availability', sa.Enum('MORNING', 'AFTERNOON', 'ALWAYS', name='time_availability_enum'), nullable=False),
    sa.Column('user_note', sa.String(length=256), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.CheckConstraint("(relation = 'ORIGINAL' AND derived_from_id IS NULL) OR (relation <> 'ORIGINAL' AND derived_from_id IS NOT NULL)", name=op.f('ck_session_professors_chk_parent_presence')),
    sa.ForeignKeyConstraint(['derived_from_id'], ['session_professors.id'], name=op.f('fk_session_professors_derived_from_id_session_professors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], name=op.f('fk_session_professors_professor_id_professors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_professors_session_id_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_professors'))
    )
    with op.batch_alter_table('session_professors', schema=None) as batch_op:
        batch_op.create_index('uq_original_prof', ['session_id', 'professor_id'], unique=True, postgresql_where=sa.text("relation = 'ORIGINAL'"))

    op.create_table('optimization_logs',
    sa.Column('opt_config_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('success', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('solver_reached_optimality', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('solver_time_limit_reached', sa.Boolean(), server_default='False', nullable=False),
    sa.Column('error_message', sa.String(length=256), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opt_config_id'], ['optimization_configurations.id'], name=op.f('fk_optimization_logs_opt_config_id_optimization_configurations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_optimization_logs'))
    )
    op.create_table('session_entries',
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=False),
    sa.Column('degree_level', sa.Enum('BACHELORS', 'MASTERS', name='degree_enum'), nullable=False),
    sa.Column('supervisor_id', sa.BigInteger(), nullable=False),
    sa.Column('supervisor2_id', sa.BigInteger(), nullable=True),
    sa.Column('supervisor_assistant_id', sa.BigInteger(), nullable=True),
    sa.Column('counter_supervisor_id', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['students.id'], name=op.f('fk_session_entries_candidate_id_students')),
    sa.ForeignKeyConstraint(['counter_supervisor_id'], ['session_professors.id'], name=op.f('fk_session_entries_counter_supervisor_id_session_professors')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_session_entries_session_id_sessions')),
    sa.ForeignKeyConstraint(['supervisor2_id'], ['session_professors.id'], name=op.f('fk_session_entries_supervisor2_id_session_professors')),
    sa.ForeignKeyConstraint(['supervisor_assistant_id'], ['session_professors.id'], name=op.f('fk_session_entries_supervisor_assistant_id_session_professors')),
    sa.ForeignKeyConstraint(['supervisor_id'], ['session_professors.id'], name=op.f('fk_session_entries_supervisor_id_session_professors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_session_entries'))
    )
    op.create_table('solution_commissions',
    sa.Column('order_key', sa.Integer(), nullable=False),
    sa.Column('morning', sa.Boolean(), server_default='True', nullable=False),
    sa.Column('duration', sa.Integer(), server_default='0', nullable=False),
    sa.Column('session_id', sa.BigInteger(), nullable=False),
    sa.Column('opt_config_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['opt_config_id'], ['optimization_configurations.id'], name=op.f('fk_solution_commissions_opt_config_id_optimization_configurations')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_solution_commissions_session_id_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_solution_commissions')),
    sa.UniqueConstraint('session_id', 'order_key', 'opt_config_id', name=op.f('uq_solution_commissions_session_id'))
    )
    op.create_table('solution_commission_professors',
    sa.Column('solution_commission_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['session_professors.id'], name=op.f('fk_solution_commission_professors_professor_id_session_professors')),
    sa.ForeignKeyConstraint(['solution_commission_id'], ['solution_commissions.id'], name=op.f('fk_solution_commission_professors_solution_commission_id_solution_commissions')),
    sa.PrimaryKeyConstraint('solution_commission_id', 'professor_id', name=op.f('pk_solution_commission_professors'))
    )
    op.create_table('solution_commission_students',
    sa.Column('solution_commission_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['solution_commission_id'], ['solution_commissions.id'], name=op.f('fk_solution_commission_students_solution_commission_id_solution_commissions')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('fk_solution_commission_students_student_id_students')),
    sa.PrimaryKeyConstraint('solution_commission_id', 'student_id', name=op.f('pk_solution_commission_students'))
    )
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('solution_commission_students')
    op.drop_table('solution_commission_professors')
    op.drop_table('solution_commissions')
    op.drop_table('session_entries')
    op.drop_table('optimization_logs')
    with op.batch_alter_table('session_professors', schema=None) as batch_op:
        batch_op.drop_index('uq_original_prof', postgresql_where=sa.text("relation = 'ORIGINAL'"))

    op.drop_table('session_professors')
    op.drop_table('optimization_configurations')
    op.drop_table('students')
    op.drop_table('sessions')
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_index('idx_professors_name_surname_unique')

    op.drop_table('professors')
    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
