"""Optimization log fields

Revision ID: fe28a282ee30
Revises: 918beebccab0
Create Date: 2025-07-24 20:12:01.588246

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = 'fe28a282ee30'
down_revision = '918beebccab0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimization_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(timezone=True), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('success', sa.Boolean(), server_default='False', nullable=False))
        batch_op.add_column(sa.Column('solver_reached_optimality', sa.Boolean(), server_default='False', nullable=False))
        batch_op.add_column(sa.Column('solver_time_limit_reached', sa.Boolean(), server_default='False', nullable=False))
        batch_op.add_column(sa.Column('error_message', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('log', sa.Text(), nullable=True))

    with op.batch_alter_table('solution_commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_commissions', schema=None) as batch_op:
        batch_op.drop_column('duration')

    with op.batch_alter_table('optimization_logs', schema=None) as batch_op:
        batch_op.drop_column('log')
        batch_op.drop_column('error_message')
        batch_op.drop_column('solver_time_limit_reached')
        batch_op.drop_column('solver_reached_optimality')
        batch_op.drop_column('success')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
