"""durations bonus freeze archive

Revision ID: 0c2e875e4113
Revises: adae8a087e20
Create Date: 2026-10-05 21:31:20.263788

"""

import warnings
from typing import TYPE_CHECKING

import sqlalchemy as sa
from alembic import op
from advanced_alchemy.types import EncryptedString, EncryptedText, GUID, ORA_JSONB, DateTimeUTC, StoredObject, PasswordHash
from sqlalchemy import Text  # noqa: F401

if TYPE_CHECKING:
    from collections.abc import Sequence

__all__ = ["downgrade", "upgrade", "schema_upgrades", "schema_downgrades", "data_upgrades", "data_downgrades"]

sa.GUID = GUID
sa.DateTimeUTC = DateTimeUTC
sa.ORA_JSONB = ORA_JSONB
sa.EncryptedString = EncryptedString
sa.EncryptedText = EncryptedText
sa.StoredObject = StoredObject

# revision identifiers, used by Alembic.
revision = '0c2e875e4113'
down_revision = 'adae8a087e20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            schema_upgrades()
            data_upgrades()

def downgrade() -> None:
    with warnings.catch_warnings():
        warnings.filterwarnings("ignore", category=UserWarning)
        with op.get_context().autocommit_block():
            data_downgrades()
            schema_downgrades()

def schema_upgrades() -> None:
    """schema upgrade migrations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('optimization_configurations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration_bachelors', sa.Integer(), server_default='15', nullable=False))
        batch_op.add_column(sa.Column('duration_masters', sa.Integer(), server_default='20', nullable=False))
        batch_op.add_column(sa.Column('duration_masters_counter', sa.Integer(), server_default='30', nullable=False))
        batch_op.add_column(sa.Column('frozen', sa.Boolean(), server_default='False', nullable=False))

    with op.batch_alter_table('session_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bonus_minutes', sa.Integer(), server_default='0', nullable=False))

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='False', nullable=False))

    with op.batch_alter_table('solution_commissions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_minutes', sa.JSON(), server_default='{}', nullable=False))

    op.create_check_constraint(
        'ck_discussion_durations_positive', 'optimization_configurations',
        'duration_bachelors > 0 AND duration_masters > 0 AND duration_masters_counter > 0')
    op.create_check_constraint(
        'ck_session_entries_bonus_minutes_non_negative', 'session_entries', 'bonus_minutes >= 0')
    # ### end Alembic commands ###

def schema_downgrades() -> None:
    """schema downgrade migrations go here."""
    op.drop_constraint('ck_session_entries_bonus_minutes_non_negative', 'session_entries', type_='check')
    op.drop_constraint('ck_discussion_durations_positive', 'optimization_configurations', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solution_commissions', schema=None) as batch_op:
        batch_op.drop_column('student_minutes')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('archived')

    with op.batch_alter_table('session_entries', schema=None) as batch_op:
        batch_op.drop_column('bonus_minutes')

    with op.batch_alter_table('optimization_configurations', schema=None) as batch_op:
        batch_op.drop_column('frozen')
        batch_op.drop_column('duration_masters_counter')
        batch_op.drop_column('duration_masters')
        batch_op.drop_column('duration_bachelors')

    # ### end Alembic commands ###

def data_upgrades() -> None:
    """Add any optional data upgrade migrations here!"""

def data_downgrades() -> None:
    """Add any optional data downgrade migrations here!"""
